# Generated by Django 4.1.5 on 2023-06-12 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_leavecalculation_leave_leave_reason_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Leave',
        ),
    ]
