# Generated by Django 4.1.5 on 2023-06-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='employee_profiles/'),
        ),
    ]
