# Generated by Django 4.1.5 on 2023-06-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employeedetail_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='profile_image',
            field=models.ImageField(default='default.png', null=True, upload_to='employee_profiles/'),
        ),
    ]
